version: '3.8'

services:
  vk_bot:
    image: ghcr.io/evgenykravchenko/vk-chatgpt-bot:latest
    container_name: vk_chatgpt_bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
